### ISSUE TITLE
如果做到不规则的圆形流布局？

### ISSUE THREAD

**Issue by beforeold** [cyrilchandelier/CCHexagonFlowLayout#4]
如何做成类似apple music选择喜欢的音乐类型/音乐人的那种圆形的流布局呢？
看这个图片效果 http://ww4.sinaimg.cn/thumbnail/687f98bbjw1extjwu2tcnj20gm0enq44.jpg

**Comment by cyrilchandelier** [comment]
Did you look at this project: https://github.com/ProudOfZiggy/SIFloatingCollection_Swift ? 

Anyway, this project issues is not the right place to talk about this, I close this issue.

**Comment by beforeold** [comment]
Thanks a lot. That is definitely what i was looking for.
